In [4]:
import numpy as np
print(((np.array([1,2,3,4,5])*2)%0.4)+2)

[2.4 2.4 2.4 2.4 2.4]


In [12]:
np.array

<function numpy.core.multiarray.array>

In [16]:
data = np.arange(6)
data

array([0, 1, 2, 3, 4, 5])

In [18]:
print(data.std())
print(data.mean())

1.707825127659933
2.5


In [1]:
x=data
y = x**2+2*x+1
y

NameError: name 'data' is not defined

In [7]:
np.zeros((2,3,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [7]:
np.full((3,5),3.14,dtype = int)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [9]:
np.linspace(5,10,5,dtype = int)

array([ 5,  6,  7,  8, 10])

In [12]:
a = np.random.normal(loc=10,scale=2,size=(3,3))
print(a.mean())
print(a.std())


9.379006851231443
1.3543034614518128


In [13]:
np.random.randint(0,10,(3,3))

array([[5, 9, 8],
       [7, 0, 2],
       [8, 1, 3]])

In [14]:
np.eye(3) ##identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.empty(2)

array([0., 0.])

In [ ]:
np.random.seed(0)
x1 = np.random.randint(10,size)

In [ ]:
x1[start:end:jump,start:end:jump]
x1[st:end:jump,st:end:jump,st:end:jump]


In [18]:
x3 = np.random.randint(10, size=(1, 4, 5))
x3

array([[[4, 2, 1, 7, 0],
        [0, 2, 0, 1, 6],
        [8, 3, 4, 7, 5],
        [6, 9, 3, 1, 5]]])

In [22]:
np.random.seed(0)
data = np.random.randint(10,size = (3,3,3))
data

array([[[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2]],

       [[4, 7, 6],
        [8, 8, 1],
        [6, 7, 7]],

       [[8, 1, 5],
        [9, 8, 9],
        [4, 3, 0]]])

In [23]:
data[2,:,:]###while extracting always cal the row you want minus 1

array([[8, 1, 5],
       [9, 8, 9],
       [4, 3, 0]])

In [24]:
data[-1,:,:]

array([[8, 1, 5],
       [9, 8, 9],
       [4, 3, 0]])

In [25]:
data[:,:,-1].T

array([[3, 6, 5],
       [9, 1, 9],
       [2, 7, 0]])

In [30]:
data[1:1]

ValueError: slice step cannot be zero

In [32]:
a=data[(data>1) & (data<8)]
a.shape=(4,4)
a

array([[5, 3, 3, 7],
       [3, 5, 2, 4],
       [7, 6, 6, 7],
       [7, 5, 4, 3]])

In [33]:
import pandas as pd

In [44]:
a = np.array([1,2,3,None,5,6])
a.shape = (2,3)
print(a)
pd.DataFrame(a)*2



[[1 2 3]
 [None 5 6]]


0   1   2
0    2   4   6
1  NaN  10  12

In [ ]:
pd.read_excel